name: ipotato_timer
description: This is a sample app to create multiple stopwatch timers
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  google_fonts: ^4.0.3
  get_it: ^7.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
